// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyANxH1NKdt0Gxs085rYzx-f4y2kNrEAOK0',
    appId: '1:443918024897:web:5c90efbf66f484ae0bd440',
    messagingSenderId: '443918024897',
    projectId: 'basics-with-flutter',
    authDomain: 'basics-with-flutter.firebaseapp.com',
    storageBucket: 'basics-with-flutter.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCYPfwlviDvb9g7LOW-xq0qdXfybAW-0Ls',
    appId: '1:443918024897:android:75a45ddcdda0c4e70bd440',
    messagingSenderId: '443918024897',
    projectId: 'basics-with-flutter',
    storageBucket: 'basics-with-flutter.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAWC2Gw440hsR_dk3MsFXXMJeRmb3s99TE',
    appId: '1:443918024897:ios:9b08c33b32a4cfa90bd440',
    messagingSenderId: '443918024897',
    projectId: 'basics-with-flutter',
    storageBucket: 'basics-with-flutter.appspot.com',
    iosClientId:
        '443918024897-odlpg8c861nnaqlkrqg9hocbl7qemriu.apps.googleusercontent.com',
    iosBundleId: 'com.example.basics',
  );
}
